version: '3.2'

services:
  web:
    image: grafana/grafana
    restart: always
    env_file: .env
    networks:
      backend:
      frontend:
        aliases:
        - "grafana"

networks:
  backend:
    external:
      name: backend
  frontend:
    external:
      name: frontend
