version: '3.2'

services:
  db:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: .env
    volumes:
    - type: volume
      source: "mariadb_data"
      target: "/var/lib/mysql"
    networks:
      backend:
        aliases:
        - "mariadb"

networks:
  backend:
    external:
      name: backend

volumes:
  mariadb_data:
