version: '3.2'

services:
  server:
    image: quay.io/ags131/screeps-server
    restart: unless-stopped
    ports:
    - "21025:21025"
    volumes:
    - type: volume
      source: "data"
      target: "/screeps"

volumes:
  data:
