version: '3.2'
services:
  screeps:
    image: screepers/screeps-launcher
    ports:
    - 21025:21025/tcp
    volumes:
    - ./config.yml:/screeps/config.yml
    - screeps-data:/screeps
    networks:
      default:
      frontend:
        aliases:
        - "screeps"
    env_file: .env
    environment:
      MONGO_HOST: mongo
      REDIS_HOST: redis
    restart: unless-stopped
    depends_on:
    - mongo
    - redis

  mongo:
    image: mongo
    volumes:
    - mongo-data:/data/db
    restart: unless-stopped

  redis:
    image: redis
    volumes:
    - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
  mongo-data:
  screeps-data:

networks:
  frontend:
    external:
      name: frontend
